version: '3.8'
services:
  db_container:
    # it is better to use specified version, to avoid breaking changes
    image: mysql:latest
    environment:
      - MYSQL_USER=bimeh
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bimeh
      - MYSQL_PASSWORD=bimeh
    container_name: db_container
    ports:
      - '3306:3306'
    volumes:
      - ../../bimeh_volume:/var/lib/mysql
    restart: on-failure

  app_container:
    container_name: app_container
    command: npm run app:run-prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - '5000:5000'
    depends_on:
      - db_container
    tty: true
    environment:
      - DATABASE_URL=mysql://root:root@db_container:3306/bimeh
      - PORT=5000
      - NODE_ENV=prod

networks:
  app-network:
